import type { StoryChoice, StoryLine } from "@/components/chatstory/ChatStoryPlayer";

export const ROOM_4B_TITLE = {
  en: "Room 4B: The Message at 2:13",
  hi: "कमरा 4B: रात 2:13 का संदेश",
};

export const ROOM_4B_HOOK = {
  en: "A message from your own number warns you not to leave the lift on the fourth floor.",
  hi: "तुम्हारे ही नंबर से आया संदेश कहता है—लिफ़्ट चौथी मंज़िल पर रुके, तो बाहर मत निकलना।",
};

export const ROOM_4B_SCENE_LABELS: Record<string, { en: string; hi: string }> = {
  "scene-1": { en: "2:13 AM · The message", hi: "रात 2:13 · संदेश" },
  "scene-2": { en: "4th floor · The landing", hi: "चौथी मंज़िल · सीढ़ियाँ" },
  "scene-3": { en: "Room 4B · The threshold", hi: "कमरा 4B · दहलीज़" },
  "scene-4": { en: "Room 4B · Don't turn around", hi: "कमरा 4B · पीछे मत देखना" },
};

export const ROOM_4B_LINES = [
  {
    idx: 1,
    speaker: "narrator",
    body: "रात के 2:13 बजे। तुम्हारा फ़ोन मेज़ पर उल्टा पड़ा है—फिर भी अपने ही नंबर से एक नया संदेश चमकता है।",
    body_en: "2:13 AM. Your phone is face down on the desk when a new message appears—from your own number.",
    next_idx: 2,
    chapter: "scene-1",
  },
  {
    idx: 2,
    speaker: "me",
    body: "मैंने ये मैसेज नहीं भेजा।",
    body_en: "I didn't send this.",
    next_idx: 3,
    chapter: "scene-1",
  },
  {
    idx: 3,
    speaker: "Echo",
    body: "लिफ़्ट चौथी मंज़िल पर रुकेगी। बाहर मत निकलना।",
    body_en: "The lift will stop at four. Don't get out.",
    next_idx: 4,
    chapter: "scene-1",
  },
  {
    idx: 4,
    speaker: "Asha",
    body: "अगर तुम्हारे ही नंबर से आया है, तो जवाब मत देना।",
    body_en: "If it came from your own number, don't reply.",
    next_idx: null,
    chapter: "scene-1",
  },
  {
    idx: 10,
    speaker: "me",
    body: "तुम्हें ये सब कैसे पता?",
    body_en: "How do you know that?",
    next_idx: 11,
    chapter: "scene-1",
  },
  {
    idx: 11,
    speaker: "Asha",
    body: "ग्यारह साल पहले नैना को भी यही मैसेज आया था। वो ऐसे कमरे में गई जिसका नाम बिल्डिंग के नक्शे में था ही नहीं।",
    body_en: "Naina got the same text eleven years ago. She went to a room that wasn't on the building plan.",
    next_idx: 12,
    chapter: "scene-1",
  },
  {
    idx: 12,
    speaker: "me",
    body: "उसके साथ क्या हुआ?",
    body_en: "What happened to her?",
    next_idx: 13,
    chapter: "scene-1",
  },
  {
    idx: 13,
    speaker: "Asha",
    body: "मैंने तीन बार दरवाज़ा खटखटाया। फिर उसकी आवाज़ मेरे फ़ोन के अंदर से आई।",
    body_en: "I knocked three times. Then her voice came from inside my phone.",
    next_idx: null,
    chapter: "scene-1",
  },
  {
    idx: 14,
    speaker: "Asha",
    body: "उसने कहा, “मैं चौथी मंज़िल पर हूँ।” गार्ड दीवार के सामने खड़े होकर उसे ढूँढ़ रहे थे।",
    body_en: "She said, “I'm on the fourth floor.” The guards were looking for her while standing in front of a wall.",
    next_idx: 15,
    chapter: "scene-2",
  },
  {
    idx: 15,
    speaker: "Echo",
    body: "तुमने कहा था कि वापस आओगे।",
    body_en: "You promised you'd come back.",
    next_idx: 16,
    chapter: "scene-2",
  },
  {
    idx: 16,
    speaker: "narrator",
    body: "आशा के नाम के नीचे टाइपिंग के तीन बिंदु उभरे, फिर गायब हो गए। तभी तुम्हारे दरवाज़े पर तीन दस्तक हुईं।",
    body_en: "Three typing dots appear beneath Asha's name, then vanish. Someone knocks on your door. Three times.",
    next_idx: 17,
    chapter: "scene-2",
  },
  {
    idx: 17,
    speaker: "me",
    body: "तुम घर पर हो न?",
    body_en: "You're home, right?",
    next_idx: 18,
    chapter: "scene-2",
  },
  {
    idx: 18,
    speaker: "Asha",
    body: "मैं वीडियो कॉल पर हूँ। गलियारे की तरफ़ मत देखना।",
    body_en: "I'm on video with you. Don't look at your hallway.",
    next_idx: 19,
    chapter: "scene-3",
  },
  {
    idx: 19,
    speaker: "narrator",
    body: "स्क्रीन पर आशा चुप रहने का इशारा करती है। उसके पीछे 4B लिखा दरवाज़ा धीरे-धीरे खुलता है।",
    body_en: "On screen, Asha presses a finger to her lips. Behind her, a door marked 4B slowly opens.",
    next_idx: 101,
    chapter: "scene-4",
  },
  {
    idx: 30,
    speaker: "narrator",
    body: "आशा अपनी लाइव लोकेशन भेजती है। नीला बिंदु कमरा 4B के दरवाज़े पर ठहरा है।",
    body_en: "Asha shares her live location. The blue dot is standing outside Room 4B.",
    next_idx: 31,
    chapter: "scene-2",
  },
  {
    idx: 31,
    speaker: "me",
    body: "तुमने कहा था कि घर पर हो।",
    body_en: "You said you were home.",
    next_idx: 32,
    chapter: "scene-2",
  },
  {
    idx: 32,
    speaker: "Asha",
    body: "मैं घर पर ही हूँ। ये नैना के फ़ोन की लोकेशन है। ग्यारह साल से उसका फ़ोन बंद है।",
    body_en: "I am home. That's Naina's phone location. Her phone has been off for eleven years.",
    next_idx: 33,
    chapter: "scene-2",
  },
  {
    idx: 33,
    speaker: "narrator",
    body: "नीला बिंदु दीवार के पार सरकता है—और तुम्हारे दरवाज़े की दूसरी तरफ़ आकर रुक जाता है।",
    body_en: "The blue dot moves through the wall—and stops on the other side of your door.",
    next_idx: 34,
    chapter: "scene-3",
  },
  {
    idx: 34,
    speaker: "Echo",
    body: "वो बाहर आ चुकी है।",
    body_en: "She's already outside.",
    next_idx: 201,
    chapter: "scene-4",
  },
  {
    idx: 40,
    speaker: "narrator",
    body: "सीढ़ियाँ तीसरी मंज़िल पर खत्म होती हैं। सामने 4B लिखा दरवाज़ा है—पर नक्शे में चौथी मंज़िल है ही नहीं।",
    body_en: "The stairs end on floor three. A door marked 4B waits there—but the building plan has no fourth floor.",
    next_idx: 41,
    chapter: "scene-2",
  },
  {
    idx: 41,
    speaker: "Kabir",
    body: "नंबर ज़ोर से मत पढ़ना।",
    body_en: "Don't read the number out loud.",
    next_idx: 42,
    chapter: "scene-2",
  },
  {
    idx: 42,
    speaker: "me",
    body: "कौन बोल रहा है?",
    body_en: "Who is this?",
    next_idx: 43,
    chapter: "scene-2",
  },
  {
    idx: 43,
    speaker: "Kabir",
    body: "उस रात मैं नाइट गार्ड था। दरवाज़ा मैंने बाहर से बंद किया था।",
    body_en: "I was the night guard that night. I locked the door from the outside.",
    next_idx: 44,
    chapter: "scene-2",
  },
  {
    idx: 44,
    speaker: "me",
    body: "नैना अंदर थी?",
    body_en: "Naina was still inside?",
    next_idx: 45,
    chapter: "scene-2",
  },
  {
    idx: 45,
    speaker: "Kabir",
    body: "मैंने तीन दस्तक सुनीं। और चलता रहा।",
    body_en: "I heard three knocks. I kept walking.",
    next_idx: 46,
    chapter: "scene-2",
  },
  {
    idx: 46,
    speaker: "Echo",
    body: "इसने अब तक पीछे मुड़कर नहीं देखा।",
    body_en: "He still hasn't looked back.",
    next_idx: null,
    chapter: "scene-3",
  },
  {
    idx: 47,
    speaker: "me",
    body: "उस कमरे के अंदर क्या है?",
    body_en: "What's inside that room?",
    next_idx: 48,
    chapter: "scene-3",
  },
  {
    idx: 48,
    speaker: "Kabir",
    body: "कुछ भी ज़िंदा नहीं। इसलिए तो मैंने दरवाज़ा बंद किया था।",
    body_en: "Nothing alive. That's why I locked it.",
    next_idx: 49,
    chapter: "scene-3",
  },
  {
    idx: 49,
    speaker: "narrator",
    body: "पुराने रेडियो में तीन बार खटखट की आवाज़ आती है। दरवाज़े के उस पार से कोई जवाब देता है।",
    body_en: "The old radio clicks three times. Something answers from the other side of the door.",
    next_idx: 50,
    chapter: "scene-3",
  },
  {
    idx: 50,
    speaker: "Kabir",
    body: "ये मैंने नहीं किया।",
    body_en: "That wasn't me.",
    next_idx: 51,
    chapter: "scene-3",
  },
  {
    idx: 51,
    speaker: "Echo",
    body: "पिछली बार भी यही कहा था।",
    body_en: "You said that last time.",
    next_idx: 301,
    chapter: "scene-4",
  },
  {
    idx: 60,
    speaker: "narrator",
    body: "दरवाज़ा खुलता है। अंदर वही गलियारा है—और फ़र्श पर तुम्हारा फ़ोन पड़ा है।",
    body_en: "The door opens onto the same hallway. Your phone is lying on the floor inside.",
    next_idx: 61,
    chapter: "scene-3",
  },
  {
    idx: 61,
    speaker: "me",
    body: "उसकी स्क्रीन जल रही है।",
    body_en: "Its screen is lit.",
    next_idx: 62,
    chapter: "scene-3",
  },
  {
    idx: 62,
    speaker: "narrator",
    body: "संदेश तुम्हारे ही नाम वाले संपर्क से आया है।",
    body_en: "The message is from a contact saved under your own name.",
    next_idx: 63,
    chapter: "scene-3",
  },
  {
    idx: 63,
    speaker: "Echo",
    body: "तुमने कहा था कि वापस आओगे।",
    body_en: "You promised you'd come back.",
    next_idx: 64,
    chapter: "scene-3",
  },
  {
    idx: 64,
    speaker: "Kabir",
    body: "अंदर मत जाना।",
    body_en: "Don't step inside.",
    next_idx: 65,
    chapter: "scene-3",
  },
  {
    idx: 65,
    speaker: "narrator",
    body: "काले फ़ोन के शीशे में दो परछाइयाँ दरवाज़े की तरफ़ देख रही हैं। तुम्हारी परछाईं उनमें से एक नहीं है।",
    body_en: "In the black phone glass, two reflections face the door. Your reflection isn't one of them.",
    next_idx: 401,
    chapter: "scene-4",
  },
  {
    idx: 101,
    speaker: "me",
    body: "आशा, पीछे मत देखना।",
    body_en: "Asha, don't turn around.",
    next_idx: 102,
    chapter: "scene-4",
  },
  {
    idx: 102,
    speaker: "Asha",
    body: "मैं तुम्हें देख रही हूँ। तुम मेरे कमरे में नहीं हो।",
    body_en: "I can see you. You're not in my room.",
    next_idx: 103,
    chapter: "scene-4",
  },
  {
    idx: 103,
    speaker: "narrator",
    body: "कॉल कट जाती है। स्क्रीन पर आशा का नाम चमकता है—कमरा 4B कॉल कर रहा है।",
    body_en: "The call drops. A new call lights up your screen: Room 4B is calling.",
    next_idx: null,
    chapter: "scene-4",
    is_terminal: true,
  },
  {
    idx: 201,
    speaker: "narrator",
    body: "दरवाज़े का हैंडल एक बार घूमता है। आशा की कॉल अब भी जुड़ी हुई है।",
    body_en: "The doorknob turns once. Asha's call is still connected.",
    next_idx: 202,
    chapter: "scene-4",
  },
  {
    idx: 202,
    speaker: "Asha",
    body: "मैंने दरवाज़े को छुआ तक नहीं। तुम भी मत छूना।",
    body_en: "I haven't touched the door. Don't touch it either.",
    next_idx: 203,
    chapter: "scene-4",
  },
  {
    idx: 203,
    speaker: "narrator",
    body: "कॉल टूटते ही ताला दूसरी तरफ़ से खुल जाता है।",
    body_en: "The call drops. The lock turns from the other side.",
    next_idx: null,
    chapter: "scene-4",
    is_terminal: true,
  },
  {
    idx: 301,
    speaker: "Kabir",
    body: "मैं उस रात भी अकेला था।",
    body_en: "I was alone that night too.",
    next_idx: 302,
    chapter: "scene-4",
  },
  {
    idx: 302,
    speaker: "narrator",
    body: "पुराना रेडियो तुम्हारी ही आवाज़ में वही वाक्य दोहराता है।",
    body_en: "The old radio repeats the sentence in your own voice.",
    next_idx: 303,
    chapter: "scene-4",
  },
  {
    idx: 303,
    speaker: "Echo",
    body: "किसने कहा कि इस बार तुम अकेले नहीं हो?",
    body_en: "Who told you that you're not alone this time?",
    next_idx: null,
    chapter: "scene-4",
    is_terminal: true,
  },
  {
    idx: 401,
    speaker: "me",
    body: "कबीर, पीछे मत देखना।",
    body_en: "Kabir, don't look behind you.",
    next_idx: 402,
    chapter: "scene-4",
  },
  {
    idx: 402,
    speaker: "Kabir",
    body: "मैं तो तुम्हारे सामने खड़ा हूँ।",
    body_en: "I'm standing right in front of you.",
    next_idx: 403,
    chapter: "scene-4",
  },
  {
    idx: 403,
    speaker: "narrator",
    body: "काँच में दूसरी परछाईं तुम्हारी तरफ़ मुड़ती है। तुमने अब तक पीछे नहीं देखा।",
    body_en: "The second reflection turns toward you in the glass. You still haven't looked back.",
    next_idx: null,
    chapter: "scene-4",
    is_terminal: true,
  },
] satisfies (StoryLine & { body_en: string })[];

export const ROOM_4B_CHOICES = [
  {
    at_idx: 4,
    position: 1,
    label: "आशा को फ़ोन करो",
    label_en: "Call Asha before moving",
    reply_body: "आशा को कॉल करता हूँ। तुम वहाँ से हटना मत।",
    reply_body_en: "I'm calling Asha. Stay where you are.",
    goto_idx: 10,
  },
  {
    at_idx: 4,
    position: 2,
    label: "सीढ़ियों से 4B तक जाओ",
    label_en: "Take the stairs to 4B",
    reply_body: "मैं 4B जा रहा हूँ। फ़ोन मत काटना।",
    reply_body_en: "I'm going to 4B. Stay on the phone.",
    goto_idx: 40,
  },
  {
    at_idx: 13,
    position: 1,
    label: "नैना के बारे में पूछो",
    label_en: "Ask what happened to Naina",
    reply_body: "नैना के साथ क्या हुआ था? सब बताओ।",
    reply_body_en: "Tell me what happened to Naina.",
    goto_idx: 14,
  },
  {
    at_idx: 13,
    position: 2,
    label: "आशा की लोकेशन माँगो",
    label_en: "Check Asha's live location",
    reply_body: "अपनी लोकेशन भेजो। अभी।",
    reply_body_en: "Send me your location. Right now.",
    goto_idx: 30,
  },
  {
    at_idx: 46,
    position: 1,
    label: "दरवाज़े के पीछे क्या है, पूछो",
    label_en: "Ask what's behind the door",
    reply_body: "कमरा 4B के अंदर क्या है?",
    reply_body_en: "What's inside Room 4B?",
    goto_idx: 47,
  },
  {
    at_idx: 46,
    position: 2,
    label: "कबीर से पहले दरवाज़ा खोलो",
    label_en: "Open the door before Kabir stops you",
    reply_body: "मैं दरवाज़ा खोल रहा हूँ।",
    reply_body_en: "I'm opening the door.",
    goto_idx: 60,
  },
] satisfies (StoryChoice & { label_en: string; reply_body_en: string })[];